### ISSUE TITLE
v0.3 Roadmap

### ISSUE THREAD

**Issue by yxonic** [yxonic/vmark#1]
# Goal

## Main objectives
* Provide a Vue component that renders Markdown to component tree (instead of HTML text).
* Provide a Vite plugin for importing Vue component, document structure, frontmatter etc. from `.md` files. Also with HMR support.
* In both cases, support a standard set of Markdown syntax and features, and provide human-friendly customization options (instead of manually configure plugins and options for each and every project).
* In both cases, support rendering external Vue components with minimal syntax change. (Our goal is to standardize Markdown rendering process. Inventing a new language or dialect doesn't help.)

## Supported Syntax
* Support 100% CommonMark & GFM.
* Optional support for frontmatter, math, custom container, inline HTML etc. (Configurable through constructor options.)
* Support only a limited set of inline HTML to prevent XSS attack.
* Support component rendering.
  * Render custom containers & custom HTML tags to a predefined set of Vue components to prevent XSS. Can always fallback to `<div>` if necessary.
  * Make no syntax change to Markdown. This is different from current solutions such as MDX.
  * Preserve the pure stateless nature of Markdown. States and custom rendering logic are fully delegated to external components.

# Implementation

## Refactor
- [ ] Decide between markdown-it and remark:
  - [ ] Compare AST difference.
  - [x] Compare plugin ecosystem.
  - [x] Compare programming ergonomics.
  - [ ] Measure migration cost.

Links:
* https://github.com/remarkjs/remark
* https://github.com/syntax-tree/mdast

## Functionality
- [ ] Standard markdown rendering.
- [ ] GFM support.
- [ ] Code highlighting with shiki. Support theme configuration.
- [ ] Math support.
- [ ] Custom container support.
- [ ] Inline HTML.
- [ ] External component rendering.
- [ ] Vite plugin to export Vue component, frontmatter and document structure.

## API
- [ ] Vue component options.
- [ ] Vite plugin options.

## Release
- [ ] Use rollup/swc/parcel to produce `cjs` and `esm` release (?)
- [ ] README update.
- [ ] Examples and documentation.

Links:
* https://vitejs.dev/guide/build.html#library-mode

## Development & Debug
- [ ] Standard markdown syntax tests.
- [ ] Configuration tests.
- [ ] Functionality tests.
